//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClanBattlesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Games_LanCenters
    {
        public int id { get; set; }
        public Nullable<int> gameId { get; set; }
        public Nullable<int> lanCenterId { get; set; }
        public string status { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual LanCenter LanCenter { get; set; }
    }
}
