//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClanBattlesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Publication
    {
        public int id { get; set; }
        public int gamerId { get; set; }
        public int gameId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string urlToImage { get; set; }
        public Nullable<System.DateTime> publicationDate { get; set; }
        public string status { get; set; }
    
        public virtual Gamer Gamer { get; set; }
    }
}
