//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClanBattlesService.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tournament
    {
        public int id { get; set; }
        public Nullable<int> lanCenterId { get; set; }
        public Nullable<int> gameId { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public Nullable<int> numberOfParticipans { get; set; }
        public string winner { get; set; }
        public string status { get; set; }
    
        public virtual LanCenter LanCenter { get; set; }
    }
}
